<?php
	require_once "Mail.php";

	function sendActivationEmail($username,$email,$firstName){
		global $IPSERVER;
		global $HOST_SMTP;
		global $PORT_SMTP;
		global $USER_SMTP;
		global $PASS_SMTP;
		global $NOREPLY_EMAIL;
		include '../config/variables.php';

		$to = $email;
		$headers = array (
			'MIME-Version' => '1.0rn',
			'Content-type' => 'text/html; charset=utf-8',
			'From' => 'Enjoy Health <'.$NOREPLY_EMAIL.'>',
			'To' => $to,
			'Cc' => '',
			'Subject' => 'Bienvenido a Enjoy Health');
			
		$body = "<html> <head>
			</head>
			<body>
				<style type='text/css'>
					.botonActivate {
						-moz-box-shadow:inset 0px 1px 0px 0px #fce2c1;
						-webkit-box-shadow:inset 0px 1px 0px 0px #fce2c1;
						box-shadow:inset 0px 1px 0px 0px #fce2c1;
						background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ffc477), color-stop(1, #fb9e25) );
						background:-moz-linear-gradient( center top, #ffc477 5%, #fb9e25 100% );
						filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffc477', endColorstr='#fb9e25');
						background-color:#ffc477;
						-moz-border-radius:6px;
						-webkit-border-radius:6px;
						border-radius:6px;
						border:1px solid #eeb44f;
						display:inline-block;
						color:#ffffff;
						font-family:arial;
						font-size:17px;
						font-weight:bold;
						padding:6px 24px;
						text-decoration:none;
						text-shadow:1px 1px 0px #cc9f52;
					}.botonActivate:hover {
						background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fb9e25), color-stop(1, #ffc477) );
						background:-moz-linear-gradient( center top, #fb9e25 5%, #ffc477 100% );
						filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fb9e25', endColorstr='#ffc477');
						background-color:#fb9e25;
					}.botonActivate:active {
						position:relative;
						top:1px;
					}
					/* This imageless css button was generated by CSSButtonGenerator.com */
				</style>
					<style type='text/css'>
						p{
							font-family: arial, sans-serif;
							font-size: 16px;
						}
						#tituloLogin{
							margin-top:5px;
							margin-bottom:5px;
							font-family: arial, sans-serif;
							color: #36C;
							font-size: 17px;
							font-weight: bold;
						}
					</style>			
					<p>Estimado " . $firstName. ",</p>
					<br/>
					<p>Te damos la más cordial bienvenida a Enjoy Health!  <br/><br/></p>
					<p>Es un placer para nosotros que seas parte de éste programa que tiene como objetivo el ayudar a mejorar la salud personal a través de la alimentación.   <br/><br/></p>
					<p>Aquí lograrás lo siguientes objetivos: <br/>br/>Lograr alcanzar tu peso ideal <br/> Mejorar tu salud <br/>Aprender a comer mejor   <br/><br/></p>
					<p>¿Qué hacer ahora?  <br/></p>
					<p>Ahora que estás inscrito, tendrás acceso a tu plan de alimentación inicial, te pedimos tomar en cuenta las siguientes indicaciones para que el programa sea efectivo.<br/> Seguir las indicaciones de la mecánica semanal. <br/> No consumir alimentos que no se encuentren mencionados.<br/> Los condimentos permitidos serán los mismos TODAS las semanas, a menos de que en la dieta de esa semana se indiquen adicionales (esto se encontrará en la pestaña de la aplicación que menciona lo “siempre permitido”.<br/> Los líquidos permitidos son los mismos TODAS las semanas, a menos de que en la dieta de esa semana se indiquen adicionales (esto se encontrará en la pestaña de la aplicación que menciona lo “siempre permitido”.<br/> Contestar el formato el día 6 de tu programa para que en el día 7 ya cuentes con el siguiente plan semanal y tengas tiempo de comprar lo que necesites.<br/> Jamás cocinar con aceite de oliva, éste sólo irá en ensaladas en estado natural si así es indicado.<br/> Es muy importante seguir las indicaciones cuando se menciona que un alimento se consuma crudo ya que cocinado cambia sus características y esto modifica los resultados así como el efecto deseado. ¡Bienvenido a la familia Enjoy!!!!   <br/><br/></p>
					<br /><br />
					<p> Saludos,</p>
					<p>EnjoyHealth</p>
			</body>
			</html>";
		
		
		$smtp = Mail::factory('smtp',
			array ('host' => $HOST_SMTP,
			'port' => $PORT_SMTP,
			'auth' => true,
			'username' => $USER_SMTP,
			'password' => $PASS_SMTP));
		
		$mail = $smtp->send($to, $headers, $body);
		
		if (PEAR::isError($mail)) {
			error_log("<p>" . $mail->getMessage() . "</p>",0);
		}
	}

	function sendRecoverPasswordEmail($username,$email,$firstName){
		global $IPSERVER;
		global $HOST_SMTP;
		global $PORT_SMTP;
		global $USER_SMTP;
		global $PASS_SMTP;
		global $NOREPLY_EMAIL;
		global $PASSPHRASE;
		include '../config/variables.php';

		$to = $email;
		$headers = array (
			'MIME-Version' => '1.0rn',
			'Content-type' => 'text/html; charset=utf-8',
			'From' => 'Enjoy Health <'.$NOREPLY_EMAIL.'>',
			'To' => $to,
			'Cc' => '',
			'Subject' => 'Recupera tu password de Enjoy Health');
			
		$body = "<html> <head>
			</head>
			<body>
				<style type='text/css'>
					.botonActivate {
						-moz-box-shadow:inset 0px 1px 0px 0px #fce2c1;
						-webkit-box-shadow:inset 0px 1px 0px 0px #fce2c1;
						box-shadow:inset 0px 1px 0px 0px #fce2c1;
						background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ffc477), color-stop(1, #fb9e25) );
						background:-moz-linear-gradient( center top, #ffc477 5%, #fb9e25 100% );
						filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffc477', endColorstr='#fb9e25');
						background-color:#ffc477;
						-moz-border-radius:6px;
						-webkit-border-radius:6px;
						border-radius:6px;
						border:1px solid #eeb44f;
						display:inline-block;
						color:#ffffff;
						font-family:arial;
						font-size:17px;
						font-weight:bold;
						padding:6px 24px;
						text-decoration:none;
						text-shadow:1px 1px 0px #cc9f52;
					}.botonActivate:hover {
						background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fb9e25), color-stop(1, #ffc477) );
						background:-moz-linear-gradient( center top, #fb9e25 5%, #ffc477 100% );
						filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fb9e25', endColorstr='#ffc477');
						background-color:#fb9e25;
					}.botonActivate:active {
						position:relative;
						top:1px;
					}
					/* This imageless css button was generated by CSSButtonGenerator.com */
				</style>
					<style type='text/css'>
						p{
							font-family: arial, sans-serif;
							font-size: 16px;
						}
						#tituloLogin{
							margin-top:5px;
							margin-bottom:5px;
							font-family: arial, sans-serif;
							color: #36C;
							font-size: 17px;
							font-weight: bold;
						}
					</style>			
					<p>Estimado " . $firstName. ",</p>
					<br/>
					<p>Gracias por utilizar el servicio de recuperacion de password de Enjoy Health  <br/><br/></p>
					<p>Para continuar te pedimos que entres a la siguiente liga : <br/><br/></p>
					<p> <a href='http://m.enjoyhealth.me/recuperaPassword.php?ui=". base64_encode($username) ."&token=".md5($PASSPHRASE)."'> Recupera tu password </a>  <br/><br/></p>
					<br /><br />
					<p> Saludos,</p>
					<p>EnjoyHealth</p>
			</body>
			</html>";
		
		
		$smtp = Mail::factory('smtp',
			array ('host' => $HOST_SMTP,
			'port' => $PORT_SMTP,
			'auth' => true,
			'username' => $USER_SMTP,
			'password' => $PASS_SMTP));
		
		$mail = $smtp->send($to, $headers, $body);
		
		if (PEAR::isError($mail)) {
			error_log("<p>" . $mail->getMessage() . "</p>",0);
		}
	}


?>