<?php
	require_once "Mail.php";

	function sendActivationEmail($username,$email,$firstName){
		global $IPSERVER;
		global $HOST_SMTP;
		global $PORT_SMTP;
		global $USER_SMTP;
		global $PASS_SMTP;
		global $NOREPLY_EMAIL;
		include '../config/variables.php';

		$to = $email;
		$headers = array (
			'MIME-Version' => '1.0rn',
			'Content-type' => 'text/html; charset=utf-8',
			'From' => 'Enjoy Health <'.$NOREPLY_EMAIL.'>',
			'To' => $to,
			'Cc' => '',
			'Subject' => 'Bienvenido a Enjoy Health');
			
		$body = "<html> <head>
			</head>
			<body>
				<style type='text/css'>
					.botonActivate {
						-moz-box-shadow:inset 0px 1px 0px 0px #fce2c1;
						-webkit-box-shadow:inset 0px 1px 0px 0px #fce2c1;
						box-shadow:inset 0px 1px 0px 0px #fce2c1;
						background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ffc477), color-stop(1, #fb9e25) );
						background:-moz-linear-gradient( center top, #ffc477 5%, #fb9e25 100% );
						filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffc477', endColorstr='#fb9e25');
						background-color:#ffc477;
						-moz-border-radius:6px;
						-webkit-border-radius:6px;
						border-radius:6px;
						border:1px solid #eeb44f;
						display:inline-block;
						color:#ffffff;
						font-family:arial;
						font-size:17px;
						font-weight:bold;
						padding:6px 24px;
						text-decoration:none;
						text-shadow:1px 1px 0px #cc9f52;
					}.botonActivate:hover {
						background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fb9e25), color-stop(1, #ffc477) );
						background:-moz-linear-gradient( center top, #fb9e25 5%, #ffc477 100% );
						filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fb9e25', endColorstr='#ffc477');
						background-color:#fb9e25;
					}.botonActivate:active {
						position:relative;
						top:1px;
					}
					/* This imageless css button was generated by CSSButtonGenerator.com */
				</style>
					<style type='text/css'>
						p{
							font-family: arial, sans-serif;
							font-size: 16px;
						}
						#tituloLogin{
							margin-top:5px;
							margin-bottom:5px;
							font-family: arial, sans-serif;
							color: #36C;
							font-size: 17px;
							font-weight: bold;
						}
					</style>			
					<div id='tituloLogin'>Bienvenido</div>
					<br /><br />
					<p>Hola " . $firstName. ",</p>
					<br/><br/>
					<p>Gracias por registrarte con nosotros , apartir de hoy podrás gozar los beneficios de EnjoyHealth.  <br/><br/><br/></p>
					<br /><br />
					<p> Saludos,</p>
					<p>EnjoyHealth</p>
			</body>
			</html>";
		
		
		$smtp = Mail::factory('smtp',
			array ('host' => $HOST_SMTP,
			'port' => $PORT_SMTP,
			'auth' => true,
			'username' => $USER_SMTP,
			'password' => $PASS_SMTP));
		
		$mail = $smtp->send($to, $headers, $body);
		
		if (PEAR::isError($mail)) {
			error_log("<p>" . $mail->getMessage() . "</p>",0);
		}
	}

?>